from __future__ import annotations

from typing import Optional, Protocol

from app.models import Document


class BackendAdapter(Protocol):
    def load_documents(self) -> list[Document]: ...
    def load_drafts(self) -> list[Document]: ...
    def save_draft(self, doc: Document) -> None: ...
    def get_document_by_id(self, doc_id: str) -> Optional[Document]: ...
